name: CI - Automatización QA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # 1. Checkout del código
      # -------------------------
      - name: Checkout del código
        uses: actions/checkout@v4

      # -------------------------
      # 2. Cache Maven dependencies
      # -------------------------
      - name: Cache Maven dependencies Web
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-web-${{ hashFiles('RetoSofka/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-web-

      - name: Cache Maven dependencies API
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-api-${{ hashFiles('RetoApi/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-api-

    
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # -------------------------
      # Proyecto Web
      # -------------------------
      - name: Compilar Web
        run: mvn clean install -DskipTests
        working-directory: RetoSofka

      - name: Ejecutar tests Web
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: mvn test -Dmaven.test.failure.ignore=true
        working-directory: RetoSofka

      - name: Generar reportes Serenity Web
        run: mvn serenity:aggregate
        working-directory: RetoSofka

      - name: Guardar reportes Web
        if: ${{ always() && (hashFiles('RetoSofka/target/site/serenity/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report-web
          path: RetoSofka/target/site/serenity/

      - name: Guardar screenshots Web
        if: ${{ always() && (hashFiles('RetoSofka/target/site/serenity/screenshots/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-web
          path: RetoSofka/target/site/serenity/screenshots/

      - name: Guardar logs Web
        if: ${{ always() && (hashFiles('RetoSofka/target/logs/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-web
          path: RetoSofka/target/logs/

      # -------------------------
      # Proyecto API
      # -------------------------
      - name: Compilar API
        run: mvn clean install -DskipTests
        working-directory: RetoApi

      - name: Ejecutar tests API
        run: mvn test -Dmaven.test.failure.ignore=true
        working-directory: RetoApi

      - name: Generar reportes Serenity API
        run: mvn serenity:aggregate
        working-directory: RetoApi

      - name: Guardar reportes API
        if: ${{ always() && (hashFiles('RetoApi/target/site/serenity/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report-api
          path: RetoApi/target/site/serenity/

      - name: Guardar screenshots API
        if: ${{ always() && (hashFiles('RetoApi/target/site/serenity/screenshots/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-api
          path: RetoApi/target/site/serenity/screenshots/

      - name: Guardar logs API
        if: ${{ always() && (hashFiles('RetoApi/target/logs/**') != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-api
          path: RetoApi/target/logs/

